# Generated by Django 6.1.1 on 2026-09-12 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('national_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('NOT_STATED', 'Prefer not to state')], max_length=20)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=30)),
                ('blood_group', models.CharField(blank=True, max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('TEMPORARILY_DEFERRED', 'Temporarily Deferred'), ('PERMANENTLY_DEFERRED', 'Permanently Deferred'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=30)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_id', models.CharField(editable=False, max_length=40, unique=True)),
                ('donation_type', models.CharField(choices=[('WHOLE_BLOOD', 'Whole Blood'), ('APHERESIS', 'Apheresis')], default='WHOLE_BLOOD', max_length=30)),
                ('collection_date', models.DateTimeField()),
                ('volume_ml', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('REGISTERED', 'Registered'), ('COLLECTED', 'Collected'), ('TESTING', 'Testing'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='REGISTERED', max_length=30)),
                ('collection_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='facilities.facility')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='donors.donor')),
            ],
        ),
        migrations.CreateModel(
            name='DeferralRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deferral_type', models.CharField(choices=[('TEMPORARY', 'Temporary'), ('PERMANENT', 'Permanent')], max_length=20)),
                ('reason', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donor_deferrals', to=settings.AUTH_USER_MODEL)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deferrals', to='donors.donor')),
            ],
        ),
        migrations.CreateModel(
            name='DonorEligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_date', models.DateTimeField(auto_now_add=True)),
                ('decision', models.CharField(choices=[('ELIGIBLE', 'Eligible'), ('DEFERRED', 'Deferred'), ('PENDING', 'Pending')], default='PENDING', max_length=20)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('haemoglobin', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=30)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('screening_notes', models.TextField(blank=True)),
                ('assessed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donor_eligibility_assessments', to=settings.AUTH_USER_MODEL)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eligibility_assessments', to='donors.donor')),
            ],
        ),
    ]
