# Generated by Django 6.1.1 on 2026-09-12 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('collected_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('COLLECTED', 'Collected'), ('RECEIVED', 'Received'), ('TESTING', 'Testing'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='COLLECTED', max_length=30)),
                ('collection_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='blood_sample', to='donors.donation')),
            ],
        ),
        migrations.CreateModel(
            name='BloodUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.CharField(editable=False, max_length=60, unique=True)),
                ('blood_group', models.CharField(max_length=10)),
                ('component_type', models.CharField(default='Whole Blood', max_length=100)),
                ('volume_ml', models.PositiveIntegerField(blank=True, null=True)),
                ('collection_date', models.DateTimeField()),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('COLLECTED', 'Collected'), ('QUARANTINED', 'Quarantined'), ('TESTING', 'Testing'), ('RELEASED', 'Released'), ('RESERVED', 'Reserved'), ('DISPATCHED', 'Dispatched'), ('TRANSFUSED', 'Transfused'), ('EXPIRED', 'Expired'), ('DISCARDED', 'Discarded')], default='QUARANTINED', max_length=30)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('storage_location', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blood_units', to='donors.donation')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blood_units', to='facilities.facility')),
            ],
        ),
        migrations.CreateModel(
            name='LaboratoryTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('test_type', models.CharField(choices=[('ABO_GROUPING', 'ABO Blood Grouping'), ('RH_TYPING', 'Rh Typing'), ('HIV', 'HIV Screening'), ('HEPATITIS_B', 'Hepatitis B Screening'), ('HEPATITIS_C', 'Hepatitis C Screening'), ('SYPHILIS', 'Syphilis Screening'), ('OTHER', 'Other')], max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('INVALID', 'Invalid')], default='PENDING', max_length=30)),
                ('result', models.CharField(blank=True, max_length=100)),
                ('result_notes', models.TextField(blank=True)),
                ('performed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='laboratory_tests_performed', to=settings.AUTH_USER_MODEL)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laboratory_tests', to='donors.bloodsample')),
            ],
        ),
    ]
