# Generated by Django 6.1.1 on 2026-09-12 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donors', '0002_bloodsample_bloodunit_laboratorytest'),
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_id', models.CharField(editable=False, max_length=60, unique=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('DISPATCHED', 'Dispatched'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('blood_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='donors.bloodunit')),
                ('from_facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_blood_transfers', to='facilities.facility')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blood_transfers_requested', to=settings.AUTH_USER_MODEL)),
                ('to_facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_blood_transfers', to='facilities.facility')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_id', models.CharField(editable=False, max_length=60, unique=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('ISSUED', 'Issued'), ('TRANSFERRED', 'Transferred'), ('TRANSFUSED', 'Transfused'), ('EXPIRED', 'Expired'), ('DISCARDED', 'Discarded')], default='AVAILABLE', max_length=30)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blood_unit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_record', to='donors.bloodunit')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_records', to='facilities.facility')),
            ],
        ),
        migrations.CreateModel(
            name='BloodReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_id', models.CharField(editable=False, max_length=60, unique=True)),
                ('patient_reference', models.CharField(blank=True, max_length=100)),
                ('blood_group', models.CharField(max_length=10)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('FULFILLED', 'Fulfilled'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blood_reservations_created', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blood_reservations', to='facilities.facility')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='inventory.inventoryrecord')),
            ],
        ),
        migrations.CreateModel(
            name='BloodIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_id', models.CharField(editable=False, max_length=60, unique=True)),
                ('patient_reference', models.CharField(blank=True, max_length=100)),
                ('clinical_reference', models.CharField(blank=True, max_length=100)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ISSUED', 'Issued'), ('RETURNED', 'Returned'), ('TRANSFUSED', 'Transfused'), ('CANCELLED', 'Cancelled')], default='ISSUED', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blood_issues', to='facilities.facility')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blood_issues_created', to=settings.AUTH_USER_MODEL)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='inventory.inventoryrecord')),
            ],
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('storage_type', models.CharField(choices=[('REFRIGERATOR', 'Blood Refrigerator'), ('FREEZER', 'Plasma Freezer'), ('PLATELET', 'Platelet Incubator'), ('OTHER', 'Other')], max_length=30)),
                ('temperature_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperature_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='storage_locations', to='facilities.facility')),
            ],
        ),
        migrations.AddField(
            model_name='inventoryrecord',
            name='storage_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_records', to='inventory.storagelocation'),
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_id', models.CharField(editable=False, max_length=60, unique=True)),
                ('movement_type', models.CharField(choices=[('RECEIVED', 'Received'), ('MOVED', 'Moved'), ('RESERVED', 'Reserved'), ('RELEASED', 'Released'), ('ISSUED', 'Issued'), ('RETURNED', 'Returned'), ('TRANSFERRED', 'Transferred'), ('DISCARDED', 'Discarded'), ('EXPIRED', 'Expired')], max_length=30)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements_created', to=settings.AUTH_USER_MODEL)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.inventoryrecord')),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_from', to='inventory.storagelocation')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_to', to='inventory.storagelocation')),
            ],
        ),
    ]
