# Generated by Django 6.1.1 on 2026-09-15 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_bloodstockalert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodtransfer',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodtransfer',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blood_transfers_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bloodtransfer',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodtransfer',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blood_transfers_rejected', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bloodtransfer',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
    ]
