# Generated by Django 6.1.1 on 2026-09-15 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_bloodtransfer_approved_at_bloodtransfer_approved_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodtransfer',
            name='dispatched_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blood_transfers_dispatched', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bloodtransfer',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blood_transfers_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
