# Generated by Django 6.1.1 on 2026-09-15 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_bloodrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(editable=False, max_length=60, unique=True)),
                ('event_type', models.CharField(choices=[('CREATED', 'Created'), ('REVIEWED', 'Reviewed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('MATCHED', 'Matched'), ('PARTIALLY_FULFILLED', 'Partially Fulfilled'), ('FULFILLED', 'Fulfilled'), ('RESERVATION_CREATED', 'Reservation Created'), ('BLOOD_ISSUED', 'Blood Issued'), ('BLOOD_RETURNED', 'Blood Returned'), ('TRANSFUSED', 'Transfused')], max_length=40)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blood_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='inventory.bloodrequest')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blood_request_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BloodRequestFulfillment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fulfillment_id', models.CharField(editable=False, max_length=60, unique=True)),
                ('units', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('RESERVED', 'Reserved'), ('ISSUED', 'Issued'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='RESERVED', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('blood_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fulfillments', to='inventory.bloodrequest')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blood_request_fulfillments_created', to=settings.AUTH_USER_MODEL)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_fulfillments', to='inventory.inventoryrecord')),
            ],
        ),
    ]
