# Generated by Django 6.1.1 on 2026-09-15 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_bloodrequestevent_bloodrequestfulfillment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequestfulfillment',
            name='units',
        ),
    ]
