# Generated by Django 6.1.1 on 2026-09-16 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
        ('inventory', '0008_remove_bloodrequestfulfillment_units'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransfusionReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_id', models.CharField(editable=False, max_length=60, unique=True)),
                ('patient_reference', models.CharField(max_length=100)),
                ('reaction_type', models.CharField(choices=[('FEBRILE_NON_HEMOLYTIC', 'Febrile Non-Hemolytic Transfusion Reaction'), ('ALLERGIC', 'Allergic Reaction'), ('ANAPHYLAXIS', 'Anaphylaxis'), ('ACUTE_HEMOLYTIC', 'Acute Hemolytic Transfusion Reaction'), ('DELAYED_HEMOLYTIC', 'Delayed Hemolytic Transfusion Reaction'), ('TRALI', 'Transfusion-Related Acute Lung Injury'), ('TACO', 'Transfusion-Associated Circulatory Overload'), ('SEPTIC', 'Septic Transfusion Reaction'), ('HYPOTENSIVE', 'Hypotensive Reaction'), ('OTHER', 'Other')], max_length=40)),
                ('severity', models.CharField(choices=[('MILD', 'Mild'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe'), ('LIFE_THREATENING', 'Life Threatening'), ('FATAL', 'Fatal')], max_length=30)),
                ('status', models.CharField(choices=[('REPORTED', 'Reported'), ('UNDER_INVESTIGATION', 'Under Investigation'), ('CONFIRMED', 'Confirmed'), ('RULED_OUT', 'Ruled Out'), ('CLOSED', 'Closed')], default='REPORTED', max_length=30)),
                ('occurred_at', models.DateTimeField()),
                ('symptoms', models.TextField(blank=True)),
                ('clinical_findings', models.TextField(blank=True)),
                ('immediate_action', models.TextField(blank=True)),
                ('treatment_given', models.TextField(blank=True)),
                ('investigation_findings', models.TextField(blank=True)),
                ('outcome', models.TextField(blank=True)),
                ('investigated_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blood_issue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfusion_reactions', to='inventory.bloodissue')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfusion_reactions_closed', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfusion_reactions', to='facilities.facility')),
                ('investigated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfusion_reactions_investigated', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfusion_reactions_reported', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
