# Generated by Django 6.1.1 on 2026-09-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_transfusionreaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfusionreaction',
            old_name='clinical_findings',
            new_name='clinical_action',
        ),
        migrations.RenameField(
            model_name='transfusionreaction',
            old_name='immediate_action',
            new_name='laboratory_findings',
        ),
        migrations.RenameField(
            model_name='transfusionreaction',
            old_name='occurred_at',
            new_name='reaction_date',
        ),
        migrations.RemoveField(
            model_name='transfusionreaction',
            name='closed_at',
        ),
        migrations.RemoveField(
            model_name='transfusionreaction',
            name='closed_by',
        ),
        migrations.RemoveField(
            model_name='transfusionreaction',
            name='investigated_at',
        ),
        migrations.RemoveField(
            model_name='transfusionreaction',
            name='investigated_by',
        ),
        migrations.RemoveField(
            model_name='transfusionreaction',
            name='treatment_given',
        ),
        migrations.AlterField(
            model_name='transfusionreaction',
            name='reaction_type',
            field=models.CharField(choices=[('FEBRILE', 'Febrile Reaction'), ('ALLERGIC', 'Allergic Reaction'), ('HEMOLYTIC', 'Hemolytic Reaction'), ('ANAPHYLACTIC', 'Anaphylactic Reaction'), ('TRALI', 'TRALI'), ('TACO', 'TACO'), ('SEPSIS', 'Septic Reaction'), ('OTHER', 'Other')], max_length=30),
        ),
    ]
