# Generated by Django 6.1.1 on 2026-09-17 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_rename_clinical_findings_transfusionreaction_clinical_action_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransfusionReactionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(editable=False, max_length=60, unique=True)),
                ('event_type', models.CharField(choices=[('REPORTED', 'Reported'), ('INVESTIGATION_STARTED', 'Investigation Started'), ('CONFIRMED', 'Confirmed'), ('RULED_OUT', 'Ruled Out'), ('CLOSED', 'Closed')], max_length=40)),
                ('previous_status', models.CharField(blank=True, max_length=30)),
                ('new_status', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfusion_reaction_events', to=settings.AUTH_USER_MODEL)),
                ('reaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='inventory.transfusionreaction')),
            ],
        ),
    ]
