# Generated by Django 6.1.1 on 2026-09-17 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_transfusionreactionevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransfusionReactionInvestigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investigation_id', models.CharField(editable=False, max_length=60, unique=True)),
                ('investigation_type', models.CharField(choices=[('CLINICAL', 'Clinical Investigation'), ('LABORATORY', 'Laboratory Investigation'), ('HAEMOVIGILANCE', 'Haemovigilance Investigation')], max_length=30)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed')], default='OPEN', max_length=30)),
                ('investigation_started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('clinical_findings', models.TextField(blank=True)),
                ('laboratory_findings', models.TextField(blank=True)),
                ('investigation_conclusion', models.TextField(blank=True)),
                ('corrective_actions', models.TextField(blank=True)),
                ('preventive_actions', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investigator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfusion_investigations', to=settings.AUTH_USER_MODEL)),
                ('reaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investigations', to='inventory.transfusionreaction')),
            ],
        ),
    ]
