# Generated by Django 6.1.1 on 2026-09-17 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
        ('inventory', '0012_transfusionreactioninvestigation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HaemovigilanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(editable=False, max_length=60, unique=True)),
                ('report_type', models.CharField(choices=[('SUSPECTED', 'Suspected Reaction'), ('CONFIRMED', 'Confirmed Reaction'), ('SERIOUS', 'Serious Adverse Reaction'), ('FATAL', 'Fatal Adverse Reaction')], max_length=30)),
                ('imputability', models.CharField(choices=[('NOT_ASSESSABLE', 'Not Assessable'), ('EXCLUDED', 'Excluded'), ('UNLIKELY', 'Unlikely'), ('POSSIBLE', 'Possible'), ('PROBABLE', 'Probable'), ('DEFINITE', 'Definite')], default='NOT_ASSESSABLE', max_length=30)),
                ('outcome', models.CharField(choices=[('RECOVERED', 'Recovered'), ('RECOVERING', 'Recovering'), ('PERSISTENT', 'Persistent Effects'), ('DISABILITY', 'Disability'), ('DEATH', 'Death'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=30)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('REVIEWED', 'Reviewed'), ('CLOSED', 'Closed')], default='DRAFT', max_length=30)),
                ('report_summary', models.TextField(blank=True)),
                ('clinical_findings', models.TextField(blank=True)),
                ('laboratory_findings', models.TextField(blank=True)),
                ('root_cause', models.TextField(blank=True)),
                ('corrective_actions', models.TextField(blank=True)),
                ('preventive_actions', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='haemovigilance_reports', to='facilities.facility')),
                ('reaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='haemovigilance_report', to='inventory.transfusionreaction')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='haemovigilance_reports_created', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='haemovigilance_reports_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransfusionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfusion_id', models.CharField(editable=False, max_length=60, unique=True)),
                ('patient_reference', models.CharField(max_length=100)),
                ('transfused_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='COMPLETED', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blood_issue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfusion_events', to='inventory.bloodissue')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfusion_events', to='facilities.facility')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfusion_events_recorded', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
