# Generated by Django 6.1.1 on 2026-09-18 10:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RMNCAHServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(editable=False, max_length=60, unique=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('category_type', models.CharField(choices=[('MATERNAL', 'Maternal Health'), ('NEWBORN', 'Newborn Health'), ('CHILD', 'Child Health'), ('ADOLESCENT', 'Adolescent Health'), ('FAMILY_PLANNING', 'Family Planning'), ('REPRODUCTIVE', 'Reproductive Health'), ('ANC', 'Antenatal Care'), ('PNC', 'Postnatal Care'), ('MATERNITY', 'Maternity Services'), ('IMMUNIZATION', 'Immunization'), ('OTHER', 'Other RMNCAH Service')], default='OTHER', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'RMNCAH Service Category',
                'verbose_name_plural': 'RMNCAH Service Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RMNCAHDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.CharField(editable=False, max_length=60, unique=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('head_name', models.CharField(blank=True, max_length=150)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rmncah_departments', to='facilities.facility')),
            ],
            options={
                'verbose_name': 'RMNCAH Department',
                'verbose_name_plural': 'RMNCAH Departments',
                'ordering': ['facility', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RMNCAHFacilityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.CharField(editable=False, max_length=60, unique=True)),
                ('rmncah_enabled', models.BooleanField(default=True)),
                ('maternal_services_available', models.BooleanField(default=False)),
                ('newborn_services_available', models.BooleanField(default=False)),
                ('child_health_services_available', models.BooleanField(default=False)),
                ('adolescent_services_available', models.BooleanField(default=False)),
                ('family_planning_available', models.BooleanField(default=False)),
                ('reproductive_health_available', models.BooleanField(default=False)),
                ('emergency_obstetric_care', models.BooleanField(default=False)),
                ('newborn_emergency_care', models.BooleanField(default=False)),
                ('caesarean_section_available', models.BooleanField(default=False)),
                ('blood_transfusion_available', models.BooleanField(default=False)),
                ('referral_services_available', models.BooleanField(default=True)),
                ('ambulance_available', models.BooleanField(default=False)),
                ('operating_hours', models.CharField(blank=True, max_length=255)),
                ('service_capacity_notes', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='rmncah_profile', to='facilities.facility')),
            ],
            options={
                'verbose_name': 'RMNCAH Facility Profile',
                'verbose_name_plural': 'RMNCAH Facility Profiles',
            },
        ),
        migrations.CreateModel(
            name='RMNCAHService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(editable=False, max_length=60, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('requires_clinical_staff', models.BooleanField(default=True)),
                ('requires_referral', models.BooleanField(default=False)),
                ('is_emergency_service', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='rmncah.rmncahservicecategory')),
            ],
            options={
                'verbose_name': 'RMNCAH Service',
                'verbose_name_plural': 'RMNCAH Services',
                'ordering': ['category', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RMNCAHServicePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_point_id', models.CharField(editable=False, max_length=60, unique=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('point_type', models.CharField(choices=[('CLINIC', 'Clinic'), ('WARD', 'Ward'), ('MATERNITY', 'Maternity'), ('LABOUR_WARD', 'Labour Ward'), ('THEATRE', 'Theatre'), ('ANC', 'ANC Clinic'), ('PNC', 'PNC Clinic'), ('CHILD_WELFARE', 'Child Welfare Clinic'), ('FAMILY_PLANNING', 'Family Planning Clinic'), ('IMMUNIZATION', 'Immunization Clinic'), ('NEWBORN', 'Newborn Unit'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('location_description', models.CharField(blank=True, max_length=255)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('is_24_hour', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_points', to='rmncah.rmncahdepartment')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rmncah_service_points', to='facilities.facility')),
            ],
            options={
                'verbose_name': 'RMNCAH Service Point',
                'verbose_name_plural': 'RMNCAH Service Points',
                'ordering': ['facility', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RMNCAHFacilityService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_service_id', models.CharField(editable=False, max_length=60, unique=True)),
                ('availability', models.CharField(choices=[('AVAILABLE', 'Available'), ('LIMITED', 'Limited'), ('TEMPORARILY_UNAVAILABLE', 'Temporarily Unavailable'), ('NOT_AVAILABLE', 'Not Available')], default='AVAILABLE', max_length=40)),
                ('is_24_hour', models.BooleanField(default=False)),
                ('emergency_available', models.BooleanField(default=False)),
                ('referral_required', models.BooleanField(default=False)),
                ('minimum_staff_required', models.PositiveIntegerField(default=0)),
                ('current_staff_count', models.PositiveIntegerField(default=0)),
                ('estimated_daily_capacity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('operating_hours', models.CharField(blank=True, max_length=255)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('configured_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rmncah_facility_services_configured', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rmncah_services', to='facilities.facility')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facility_services', to='rmncah.rmncahservice')),
                ('service_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facility_services', to='rmncah.rmncahservicepoint')),
            ],
            options={
                'verbose_name': 'Facility RMNCAH Service',
                'verbose_name_plural': 'Facility RMNCAH Services',
                'ordering': ['facility', 'service__category', 'service__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='rmncahdepartment',
            constraint=models.UniqueConstraint(fields=('facility', 'code'), name='unique_rmncah_department_code_per_facility'),
        ),
        migrations.AddConstraint(
            model_name='rmncahservicepoint',
            constraint=models.UniqueConstraint(fields=('facility', 'code'), name='unique_rmncah_service_point_code_per_facility'),
        ),
        migrations.AddConstraint(
            model_name='rmncahfacilityservice',
            constraint=models.UniqueConstraint(fields=('facility', 'service'), name='unique_rmncah_service_per_facility'),
        ),
    ]
